action :add do
  environment_name = replace_spaces new_resource.environment_variable
  if !new_resource.value.nil?
    Chef::Log.info("Adding #{environment_name}.sh to /etc/profile.d/")
    file_contents = "# This file was generated by Chef for #{node["fqdn"]}\n"
    file_contents += "export #{environment_name}='#{new_resource.value}'"
    file "/etc/profile.d/#{environment_name}.sh" do
      owner "root"
      group "root"
      mode "0755"
      content file_contents
    end
    new_resource.updated_by_last_action(true)
  end
end

action :remove do
  environment_name = replace_spaces new_resource.environment_variable
  if ::File.exists?("/etc/profile.d/#{environment_name}.sh")
    Chef::Log.info("Removing #{environment_name}.sh from /etc/profile.d/")
    file "/etc/profile.d/#{environment_name}.sh" do
      action :delete
    end
    new_resource.updated_by_last_action(true)
  end
end

def replace_spaces(name)
  name = name.gsub(/ /,"_")
end
